export default function NotFound() {
  return (
    <div className="container relative mx-auto mb-4 bg-purple-900 lg:mb-0">
        <div className=" grid grid-flow-col ">
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
        </div>
        <div className=" grid grid-flow-col ">
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
        </div>
        <div className="mb-px grid grid-flow-col ">
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
        </div>
        <div className="mb-px grid grid-flow-col ">
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
        </div>
        <div className="mb-px grid grid-flow-col ">
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
        </div>
        <div className="mb-px grid grid-flow-col ">
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
        </div>
        <div className="mb-px grid grid-flow-col ">
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
        </div>
        <div className="grid grid-flow-col ">
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
        </div>
        <div className=" grid grid-flow-col ">
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
            <div className="errorPage-square"></div>
        </div>
        <div className="errorPage-radialGradient absolute inset-0"></div>
        <div className="absolute inset-0 z-10">
            <div className=" grid grid-flow-col ">
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
            </div>
            <div className=" grid grid-flow-col ">
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                {/* <div className="errorPage-square"></div> */}
            </div>
            <div className="mb-px grid grid-flow-col ">
                {/* <div className="errorPage-square"></div> */}
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-numberBox"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-numberBox"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-numberBox errorPage-numberBox2"></div>
                <div className="errorPage-numberBox errorPage-numberBox2"></div>
                <div className="errorPage-numberBox errorPage-numberBox2"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-numberBox errorPage-numberBox3"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-numberBox errorPage-numberBox3"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
            </div>
            <div className="mb-px grid grid-flow-col ">
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-numberBox"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-numberBox"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-numberBox errorPage-numberBox2"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-numberBox errorPage-numberBox2"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-numberBox errorPage-numberBox3"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-numberBox errorPage-numberBox3"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
            </div>
            <div className="mb-px grid grid-flow-col ">
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-numberBox"></div>
                <div className="errorPage-numberBox"></div>
                <div className="errorPage-numberBox"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-numberBox errorPage-numberBox2"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-numberBox errorPage-numberBox2"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-numberBox errorPage-numberBox3"></div>
                <div className="errorPage-numberBox errorPage-numberBox3"></div>
                <div className="errorPage-numberBox errorPage-numberBox3"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
            </div>
            <div className="mb-px grid grid-flow-col ">
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-numberBox"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-numberBox errorPage-numberBox2"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-numberBox errorPage-numberBox2"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-numberBox errorPage-numberBox3"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
            </div>
            <div className="mb-px grid grid-flow-col ">
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-numberBox"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-numberBox errorPage-numberBox2"></div>
                <div className="errorPage-numberBox errorPage-numberBox2"></div>
                <div className="errorPage-numberBox errorPage-numberBox2"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                {/* <div className="errorPage-square"></div> */}
                <div className="errorPage-numberBox errorPage-numberBox3"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
            </div>
            <div className="grid grid-flow-col ">
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
            </div>
            <div className="grid grid-flow-col ">
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
                <div className="errorPage-square"></div>
            </div>
        </div>
    </div>
  );
}
